
# 1).  List the top 3 customers who have placed the highest number of orders.

SELECT customer_id, COUNT(order_id) AS total_orders
FROM order_detail
GROUP BY customer_id
ORDER BY total_orders DESC
LIMIT 3;

# 2).  Find the restaurant that has received the highest average rating.

SELECT restaurant_name, rrating
FROM restaurant
ORDER BY rrating DESC
LIMIT 1;

# 3). List all orders delivered in under 30 minutes.

SELECT *,
TIMESTAMPDIFF(MINUTE, order_time, delivered_time) AS delivery_time
FROM order_detail
WHERE TIMESTAMPDIFF(MINUTE, order_time, delivered_time) < 30;

# 4). Total revenue generated by each food item

 SELECT f.food_id, f.food_name,
SUM(ofd.quantity * f.price_per_unit) AS total_revenue
FROM order_food ofd
JOIN foods f ON ofd.food_id = f.food_id
GROUP BY f.food_id, f.food_name
ORDER BY total_revenue DESC;

# 5). Second highest revenue-generating restaurant

SELECT r.restaurant_name,
SUM(ofd.quantity * f.price_per_unit) AS total_revenue
FROM order_food ofd
JOIN foods f ON ofd.food_id = f.food_id
JOIN order_detail od ON ofd.order_id = od.order_id
JOIN restaurant r ON od.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_name
ORDER BY total_revenue DESC
LIMIT 1 OFFSET 1;


# 6). Find the 5 most popular food items (based on quantity sold)

SELECT f.food_id, f.food_name,
SUM(ofd.quantity) AS total_quantity_sold
FROM order_food ofd
JOIN foods f ON ofd.food_id = f.food_id
GROUP BY f.food_id, f.food_name
ORDER BY total_quantity_sold DESC
LIMIT 5;

# 7). Top 3 Zomato employees with highest average delivery ratings

SELECT employee_id, employee_name, employee_avg_rating
FROM zomato_employee
ORDER BY employee_avg_rating DESC
LIMIT 3;

# 8).  Month with highest number of total orders

SELECT MONTH(order_time) AS month,
COUNT(order_id) AS total_orders
FROM order_detail
GROUP BY MONTH(order_time)
ORDER BY total_orders DESC
LIMIT 1;

# 9). Average order amount for each customer (descending)

SELECT od.customer_id,
AVG(ofd.quantity * f.price_per_unit) AS avg_order_amount
FROM order_detail od
JOIN order_food ofd ON od.order_id = ofd.order_id
JOIN foods f ON ofd.food_id = f.food_id
GROUP BY od.customer_id
ORDER BY avg_order_amount DESC;

# 10). Most frequent customer for each restaurant

SELECT restaurant_id, customer_id, COUNT(order_id) AS total_orders
FROM order_detail
GROUP BY restaurant_id, customer_id
ORDER BY restaurant_id, total_orders DESC;

# 11).  Total number of weekend orders

SELECT COUNT(order_id) AS weekend_orders
FROM order_detail
WHERE DAYOFWEEK(order_time) IN (1,7);

# 12).  Average delivery time (Weekday vs Weekend)

SELECT 
CASE 
    WHEN DAYOFWEEK(order_time) IN (1,7) THEN 'Weekend'
    ELSE 'Weekday'
END AS day_type,
AVG(TIMESTAMPDIFF(MINUTE, order_time, delivered_time)) AS avg_delivery_time
FROM order_detail
GROUP BY day_type;

#13).  Top 5 most expensive food items

SELECT food_id, food_name, price_per_unit
FROM foods
ORDER BY price_per_unit DESC
LIMIT 5;

# 14). Restaurant with most diverse menu (highest number of food items)

SELECT r.restaurant_name,
COUNT(DISTINCT ofd.food_id) AS total_food_items
FROM restaurant r
JOIN order_detail od ON r.restaurant_id = od.restaurant_id
JOIN order_food ofd ON od.order_id = ofd.order_id
GROUP BY r.restaurant_name
ORDER BY total_food_items DESC
LIMIT 1;

# 15). Total payment amount for each payment type

select pt.payment_type, sum(order_total_amount) as total_payment_type
from payment_table pt
join
(
select od.order_id,
sum(od.quantity * f.price_per_unit) as order_total_amount
from order_food od
join foods f on od.food_id = f.food_id
group by od.order_id
) as order_totals on pt.order_id = order_totals.order_id
group by pt.payment_type
order by total_payment_type desc;